# Generated by Cypress Editor
# 04/01/2022, 15:10:17
# 261f7e0a-e881-42eb-b8d2-9ccca23108ec
# Blank Tcl Document - Blank tcl document
# THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
# PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
# FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
# Generated by Cypress Editor
wipe

set inFile cyclic.txt

##_XXXXXXXXXXXXXXXXX----- Logical Switch for Analysis ------XXXXXXXXXXX_##
set Gravity 1
set Pushover 0
set BNWF 0
set CyclicPushover 0
set Earthquake 0
set stressstrain 1
set slip 0


set outpath 3dmodel-noslip-g
file mkdir $outpath
puts "The output directory name is: $outpath"

model BasicBuilder -ndm 3 -ndf 6
source 3dprops_mm.tcl

set geomlinear 1
set geompdelta 2
# Put 4 for Concrete07, put 7 for Concrete01
set concmattag 4
geomTransf Linear $geomlinear 0 0 1
geomTransf PDelta $geompdelta 0 0 1
if {$BNWF} {
puts "BNWF model is activated."
    set midnode_1 1
        set midnode_2 2
        set midnode_3 3
        node $midnode_1 2000. 0. 0.
        node $midnode_2 7000. 0. 0.
        node $midnode_3 12000. 0. 0.
        node 100 2000. 0. 0.
        node 200 7000. 0. 0.
        node 300 12000. 0. 0.
        #fix $midnode_1 1 1 1
        #fix $midnode_2 1 1 1
        #fix $midnode_3 1 1 1
    } else { puts "Fixed model is activated."
        set midnode_1 1
        set midnode_2 2
        set midnode_3 3
        node $midnode_1 2000. 0. 0.
        node $midnode_2 7000. 0. 0.
        node $midnode_3 12000. 0. 0.
        if {$slip} { puts "Slip model is activated."
        node 100 2000. 0. 0.
        node 200 7000. 0. 0.
        node 300 12000. 0. 0.
        fix 100 1 1 1 1 1 1
        fix 200 1 1 1 1 1 1
        fix 300 1 1 1 1 1 1
        
        fix 1 1 0 1 1 1 0
        fix 2 1 0 1 1 1 0
        fix 3 1 0 1 1 1 0 
        } else {
            fix 1 1 1 1 1 1 1
            fix 2 1 1 1 1 1 1
            fix 3 1 1 1 1 1 1
        }
        
    }
    
    
    

# SUPPORT NODES

# STOREY NODES
for {set iy 1} {$iy <= 3} {incr iy} {
    node [expr ($iy-1)*9+4] 0. [expr $iy*$H] 0.
    node [expr ($iy-1)*9+5] 2000. [expr $iy*$H] 0. -mass $m1 0. 0. 0. 0. 0.
    node [expr ($iy-1)*9+6] 3500. [expr $iy*$H] 0.
    node [expr ($iy-1)*9+7] 5500. [expr $iy*$H] 0.
    node [expr ($iy-1)*9+8] 7000. [expr $iy*$H] 0. -mass $m2 0. 0. 0. 0. 0.
    node [expr ($iy-1)*9+9] 8500. [expr $iy*$H] 0.
    node [expr ($iy-1)*9+10] 10500. [expr $iy*$H] 0.
    node [expr ($iy-1)*9+11] 12000. [expr $iy*$H] 0. -mass $m3 0. 0. 0. 0. 0.
    node [expr ($iy-1)*9+12] 14000. [expr $iy*$H] 0.
    #fix [expr ($iy-1)*9+4] 0 0 1 1 1 0
    #fix [expr ($iy-1)*9+5] 0 0 1 1 1 0 
    #fix [expr ($iy-1)*9+6] 0 0 1 1 1 0
    #fix [expr ($iy-1)*9+7] 0 0 1 1 1 0 
    #fix [expr ($iy-1)*9+8] 0 0 1 1 1 0 
    #fix [expr ($iy-1)*9+9] 0 0 1 1 1 0 
    #fix [expr ($iy-1)*9+10] 0 0 1 1 1 0 
    #fix [expr ($iy-1)*9+11] 0 0 1 1 1 0 
    #fix [expr ($iy-1)*9+12] 0 0 1 1 1 0 
   
    }

equalDOF 23 29 1  
equalDOF 14 20 1  
equalDOF 5 11 1  
#equalDOF 2 3 1


#uniaxialMaterial Steel02 $matTag $Fy $E $b $R0 $cR1 $cR2 <$a1 $a2 $a3 $a4 $sigInit>
uniaxialMaterial Steel02 1 $fy1 $E $b $R0 $R1 $R2
uniaxialMaterial Steel02 2 $fy2 $E $b $R0 $R1 $R2
uniaxialMaterial Steel02 3 $fy3 $E $b $R0 $R1 $R2
uniaxialMaterial Bond_SP01 22 $fy2 $Sy $fu2 $Su $bbond $Rbond
#uniaxialMaterial Bond_SP01 22 452. $Sy 645. $Su $bbond $Rbond
set st_18_mm 1
set st_14_mm 2
set st_8_mm 3
set st_bond 22


#uniaxialMaterial Concrete07 $matTag $fc $ec $Ec $ft $et $xp $xn $r
#Confined Concrete
uniaxialMaterial Concrete07 4 $fc1 $ec $Ec $fct $et 1.5 1.5 2.65
uniaxialMaterial Concrete07 5 $fc2 $ec $Ec $fct $et 1.5 1.5 2.65
uniaxialMaterial Concrete07 6 $fc3 $ec $Ec $fct $et 1.5 1.5 2.65

uniaxialMaterial Concrete07 100 $fc100 $ec $Ec100 $fct $et 1.5 1.5 2.65
uniaxialMaterial Concrete07 200 $fc100 $ec $Ec100 $fct $et 1.9 1.9 3.65
#Unconfined Concrete
uniaxialMaterial Concrete07 41 $fc1 $ec $Ec $fct $et 1.9 1.9 3.65
uniaxialMaterial Concrete07 51 $fc2 $ec $Ec $fct $et 1.9 1.9 3.65
uniaxialMaterial Concrete07 61 $fc3 $ec $Ec $fct $et 1.9 1.9 3.65

#Concrete01 Material
#Confined
uniaxialMaterial Concrete01 7 $fc1 $ec $fp1 $ecuc 
uniaxialMaterial Concrete01 8 $fc2 $ec $fp2 $ecuc 
uniaxialMaterial Concrete01 9 $fc3 $ec $fp3 $ecuc 

uniaxialMaterial Concrete01 71 $fc1 $ec $fp1 $ecu 
uniaxialMaterial Concrete01 81 $fc2 $ec $fp2 $ecu 
uniaxialMaterial Concrete01 91 $fc3 $ec $fp3 $ecu

set cortag100 100
set covtag100 200
source 3dfiber_mm.tcl

set secnum 5; #Integration point numbers
set geomcol $geompdelta
set geombeam $geomlinear

for {set ij 1} {$ij <= 3} {incr ij} {
    element dispBeamColumn [expr 4+11*($ij-1)] [expr 4+($ij-1)*9] [expr 4+($ij-1)*9+1] $secnum [expr 3+($ij-1)*4] $geombeam
    element dispBeamColumn [expr 5+11*($ij-1)] [expr 5+($ij-1)*9] [expr 5+($ij-1)*9+1] $secnum [expr 3+($ij-1)*4] $geombeam
    element dispBeamColumn [expr 6+11*($ij-1)] [expr 6+($ij-1)*9] [expr 6+($ij-1)*9+1] $secnum [expr 4+($ij-1)*4] $geombeam
    element dispBeamColumn [expr 7+11*($ij-1)] [expr 7+($ij-1)*9] [expr 7+($ij-1)*9+1] $secnum [expr 3+($ij-1)*4] $geombeam
    element dispBeamColumn [expr 8+11*($ij-1)] [expr 8+($ij-1)*9] [expr 8+($ij-1)*9+1] $secnum [expr 3+($ij-1)*4] $geombeam
    element dispBeamColumn [expr 9+11*($ij-1)] [expr 9+($ij-1)*9] [expr 9+($ij-1)*9+1] $secnum [expr 4+($ij-1)*4] $geombeam
    element dispBeamColumn [expr 10+11*($ij-1)] [expr 10+($ij-1)*9] [expr 10+($ij-1)*9+1] $secnum [expr 3+($ij-1)*4] $geombeam
    element dispBeamColumn [expr 11+11*($ij-1)] [expr 11+($ij-1)*9] [expr 11+($ij-1)*9+1] $secnum [expr 3+($ij-1)*4] $geombeam
}


element dispBeamColumn 1 $midnode_1 5 $secnum 1 $geomcol
element dispBeamColumn 2 $midnode_2 8 $secnum 2 $geomcol
element dispBeamColumn 3 $midnode_3 11 $secnum 1 $geomcol
element dispBeamColumn 12 5 14 $secnum 5 $geomcol
element dispBeamColumn 13 8 17 $secnum 6 $geomcol
element dispBeamColumn 14 11 20 $secnum 5 $geomcol
element dispBeamColumn 23 14 23 $secnum 9 $geomcol
element dispBeamColumn 24 17 26 $secnum 10 $geomcol
element dispBeamColumn 25 20 29 $secnum 9 $geomcol
#element dispBeamColumn [expr 2+11*($ij-1)] [expr 1+$ij] [expr 1+$ij+4] $secnum [expr 2+($ij-1)*4] $geomcol
#element dispBeamColumn [expr 3+11*($ij-1)] [expr 2+$ij] [expr 2+$ij+4] $secnum [expr 1+($ij-1)*4] $geomcol
#element dispBeamColumn [expr 1+11*($ij-1)] [expr 5+($ij-2)*9] [expr 5+($ij-2)*9+9] $secnum [expr 1+($ij-1)*4] $geomcol 
#element dispBeamColumn [expr 2+11*($ij-1)] [expr 6+($ij-2)*9] [expr 6+($ij-2)*9+9] $secnum [expr 2+($ij-1)*4] $geomcol
#element dispBeamColumn [expr 3+11*($ij-1)] [expr 7+($ij-2)*9] [expr 7+($ij-2)*9+9] $secnum [expr 1+($ij-1)*4] $geomcol
#element dispBeamColumn 100 100 $midnode_1 $secnum 100 $geomcol
#element dispBeamColumn 200 200 $midnode_2 $secnum 200 $geomcol
#element dispBeamColumn 300 300 $midnode_3 $secnum 100 $geomcol
if {$slip} {
    element zeroLengthSection 100 100 $midnode_1 100 -orient 0 1 0 -1 0 0
    element zeroLengthSection 200 200 $midnode_2 200 -orient 0 1 0 -1 0 0
    element zeroLengthSection 300 300 $midnode_3 100 -orient 0 1 0 -1 0 0
}
if {$BNWF} {
    #ShallowFoundationGen 1 1 propy_clay.tcl 5
    #ShallowFoundationGen 2 2 propy_clay.tcl 5  
    #ShallowFoundationGen 3 3 propy_clay.tcl 5
    source Foundation_1.tcl
    source Foundation_2.tcl
    source Foundation_3.tcl 
}


# XXXXXXXXXXXXXXXXXX---EIGEN ANALYSIS---XXXXXXXXXXXXXXXXXXXXXXXXXXX 
set numModes 3
set lambda [eigen  $numModes];
set omega {}
set f {}
set T {}
set pi 3.141593
source frame_recorders_3d.tcl
foreach lam $lambda {
    lappend omega [expr sqrt($lam)]
    lappend f [expr sqrt($lam)/(2*$pi)]
    lappend T [expr (2*$pi)/sqrt($lam)]
}

puts "The modal period values (second): $T "
puts "The modal frequency values (Hertz): $f "

set ts_con 1
set ts_lin 2
wipeAnalysis
# XXXXXXXXXXXXX---GRAVITY LOADS---XXXXXXXXXXXXXXXXXXX
set Wg [expr -14062.5/1000.]
set Qg [expr -24000.]
set Qg_1 [expr -77343.75-13333.]
set Qg_2 [expr -132375.-40000.]
set Qg_3 [expr -125343.75-73333.]
timeSeries Constant $ts_con
timeSeries Linear $ts_lin

source 3d_analysis.tcl
